disabled_rules:
  - closure_parameter_position
  - cyclomatic_complexity
  - file_length
  - function_body_length
  - todo
  - type_body_length

opt_in_rules:
  - accessibility_label_for_image

large_tuple: 3

nesting:
  # Allows nested objects under JSON:API types, with CodingKeys nested under that
  type_level: 2
