disabled_rules:
  - closure_parameter_position
  - cyclomatic_complexity
  - file_length
  - todo

opt_in_rules:
  - accessibility_label_for_image

nesting:
  # Allows nested objects under JSON:API types, with CodingKeys nested under that
  type_level: 2
