name: Test
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: List simulators
        run: xcrun simctl list
      - name: Build and run tests
        run: exec ./.github/scripts/test.sh
